sudo: required

language: node_js

services:
  - docker

before_install:
  - docker pull drachtio/drachtio-server:latest
  - docker pull davehorton/rtpengine:latest
  - docker pull drachtio/sipp:latest
  - docker images

script:
  - npm test
